# Generated by Django 2.2.3 on 2019-07-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'Tiny'), ('M', 'Medium'), ('L', 'Large')], max_length=1),
        ),
    ]
